<? head('', array('generic.css')); ?>

<div id="side">
   <? header_box(); ?>
   </ul>
</div>

<div id="content">
   <div id="generic">
      <img src="assets/generic-top.jpg" alt="" />
      
      <h1>About ScenicOrNot</h1>
      
      <dl class="content">
         <dt>What is this site?</dt>
         <dd>
            It&rsquo;s a game &mdash; pit your aesthetic judgements against other 
            users, and discover the lovely and not so lovely corners of the UK.
         </dd>
      
         <dt>Where are all the pictures from?</dt>
         <dd>
            The lovely people at <a href="http://www.geograph.org.uk">Geograph</a>.
         </dd>
      
         <dt>Why did you build it?</dt>
         <dd>
            We want to gather a freely available nation-wide dataset of
            scenicness, to use for a <a href="http://mapumental.channel4.com/">secret project</a>.
         </dd>
      
         <dt>Can I download the data generated by this site?</dt>
         <dd>            
	    <p>Sure, we&rsquo;re happy to
            make the data available for other people to use under the <a href="http://creativecommons.org/licenses/by-nc/3.0/">Creative
            Commons Attribution Noncommercial 3 Licence</a>.</p>

	    <p><a href="/votes.tsv">votes.tsv</a> is a <acronym title="tab separated value">TSV</acronym>
	    file of all photos that have been rated 3 times or more. The
	    columns are ID, latitude, longitude, average rating, population
	    variance, the votes (comma separated), and the Geograph URI for the
	    photo; the file updates weekly.</p>
            
            <p>There are 217,000 images (one for each of nearly 95% of the 1km grid
            squares in the UK), and we&rsquo;re making sure each one is rated 3 times by
            different people, to help limit abuse, or the impact of people with
            terrible taste.</p>
         </dd>
         
         <dt>What if a photo is unrepresentative of the scenicness of a grid square?</dt>
         <dd>
            At first, there&rsquo;s nothing we can do. When we hit 651,000
            plays we can add a different photo for each grid square, and
            hopefully that will help even out bad photos.
         </dd>

         <dt>Who built it?</dt>
         <dd>
            This site was built by <a href="http://www.thedextrousweb.com">The 
            Dextrous Web</a> for <a href="http://www.mysociety.org">mySociety</a>.
         </dd>
               
         <dt>How do I get in touch?</dt>
         <dd>Email <a href="mailto:team&#64;mysociety.org">team&#64;mysociety.org</a>.</dd>
      
      </dl>
   </div>
   <img src="assets/generic-bottom.jpg" alt="" />
</div>

<? foot(); ?>
